### PR TITLE
add download command for en_core_web_md to Dockerfile

### PR DESCRIPTION
**Pull request by chuckcurtis**

### CODE REVIEW

**Comment by amqdn** [comment]
Hey,

Have you tried deploying on Elastic Beanstalk with this change? I remember having issues downloading the tokenizer via Hugging Face, but maybe that's because I didn't have internet access once the Streamlit app was launched.

**Comment by chuckcurtis** [comment]
> Hey,
> 
> Have you tried deploying on Elastic Beanstalk with this change? I remember having issues downloading the tokenizer via Hugging Face, but maybe that's because I didn't have internet access once the Streamlit app was launched.

Hey, I haven't yet; I can try that in the morning.

**Comment by chuckcurtis** [comment]
I was able to deploy on EB successfully

**Comment by amqdn** [comment]
Okay, great! Thanks for confirming.

**Pull request merged**
